import torch


def vector_add(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor: ...


def vector_add_raw(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor: ...


def cpu_large_vector_add_async(a: torch.Tensor, b: torch.Tensor, buffer_size: int = 1024) -> torch.Tensor: ...


def saxpy(x: torch.Tensor, y: torch.Tensor, a: float) -> torch.Tensor: ...


def matrix_add(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor: ...


def rgb_to_grayscale(inp: torch.Tensor) -> torch.Tensor: ...
